CREATE TABLE Dependencies (modified NUMERIC, after NUMERIC, before NUMERIC);
CREATE TABLE Priority (id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE Status (modified NUMERIC, id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE Tagged (modified NUMERIC, tag NUMERIC, task NUMERIC);
CREATE TABLE Tags (modified NUMERIC, id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE Tasks (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, created NUMERIC, modified NUMERIC, priority NUMERIC, due NUMERIC, status NUMERIC);
