CREATE TABLE Dependencies (after NUMERIC, before NUMERIC);
CREATE TABLE Status (id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE Tagged (tag NUMERIC, task NUMERIC);
CREATE TABLE Tags (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT);
CREATE TABLE Tasks (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, created NUMERIC, modified NUMERIC, priority NUMERIC, due NUMERIC, status NUMERIC);

